flags: {}
packages:
- '.'
resolver: nightly-2019-03-03
extra-deps: [messagepack-0.5.4]

allow-newer: true

nix:
  # Not using pure here because it is very practical to inherit
  # $NVIM_LISTEN_ADDRESS when developing and debugging plugins.
  pure: false

  packages:
  - zlib
  - neovim # for api generation
